name: Force Validation
on:
  workflow_dispatch:

jobs:
  force-validate-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Pip install
        run: pip install -r requirements.txt
      - name: Validate Catalog Items
        run: python scripts/validate_catalog.py -f
        env:
          GSTORAGE_API_KEY: ${{ secrets.GSTORAGE_API_KEY }}
